# Generated by Django 4.0.3 on 2022-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_active_remove_listing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='on_watch_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
