# Generated by Django 4.0.4 on 2022-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_on_watch_list_alter_listing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='on_watch_list',
        ),
        migrations.AddField(
            model_name='listing',
            name='on_watch_list',
            field=models.BooleanField(default=False),
        ),
    ]
